// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghpswwhpuvdgvdftoqsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdocHN3d2hwdXZkZ3ZkZnRvcXNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYzODc4ODgsImV4cCI6MjA5MTk2Mzg4OH0.-7dM04hryWfK85xf1MpWvSiPDueRVL1ZMqNsg1btDiQ";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});