// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbmkmkizthwqgqdvdkef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNibWtta2l6dGh3cWdxZHZka2VmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYyOTg0NTEsImV4cCI6MjA5MTg3NDQ1MX0.r70w7evCSuWVXeMDToJdWVexuca-bP1j3w3fI0asKxc";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});